# Generated by Django 5.1.3 on 2024-11-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='main_image',
            field=models.ImageField(default='static/image/defaultmain.jpg', upload_to='static/image/main'),
        ),
    ]
