# Generated by Django 5.1.3 on 2024-11-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='main_image',
            field=models.ImageField(default='static/image/defaultmain.jpg', upload_to='media/main'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='media/rooms'),
        ),
    ]
