# Generated by Django 5.1.3 on 2024-11-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_hostel_main_image_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
