# Generated by Django 5.1.3 on 2024-11-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_booking_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_number',
        ),
    ]
